import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 1,
      nameEN: 'Free Shirt',
      slugEN: 'free-shirt',
      categoryEN: 'Shirts',
      descriptionEN: 'A popular shirt',
      nameIT: 'Maglietta Gratis',
      slugIT: 'maglietta-gratis',
      categoryIT: 'Maglieria',
      descriptionIT: 'Una maglietta molto popolare',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
    {
      id: 2,
      nameEN: 'Fit Shirt',
      slugEN: 'fit-shirt',
      categoryEN: 'Shirts',
      descriptionEN: 'A popular shirt',
      nameIT: 'Maglietta Aderente',
      slugIT: 'fit-shirt',
      categoryIT: 'Maglieria',
      descriptionIT: 'Una maglietta aderente molto popolare',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
    },
    {
      id: 3,
      nameEN: 'Slim Shirt',
      slugEN: 'slim-shirt',
      categoryEN: 'Shirts',
      descriptionEN: 'A popular shirt',
      nameIT: 'Maglietta magra',
      slugIT: 'slim-shirt',
      categoryIT: 'Maglieria',
      descriptionIT: 'Una maglietta magra molto popolare',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
    },
    {
      id: 4,
      nameEN: 'Golf Pants',
      slugEN: 'golf-pants',
      categoryEN: 'Pants',
      descriptionEN: 'Smart looking pants',
      nameIT: 'Pantaloni da Golf',
      slugIT: 'golf-pants',
      categoryIT: 'Pantaloni',
      descriptionIT: 'Un panta-golf molto popolare',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
    },
    {
      id: 5,
      nameEN: 'Fit Pants',
      slugEN: 'fit-pants',
      categoryEN: 'Pants',
      descriptionEN: 'A popular pants',

      nameIT: 'Panta Aderente',
      slugIT: 'fit-pants',
      categoryIT: 'Pantaloni',
      descriptionIT: 'Un fit-pants molto popolare',

      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
    },
    {
      id: 6,
      nameEN: 'Classic Pants',
      slugEN: 'classic-pants',
      categoryEN: 'Pants',
      descriptionEN: 'A popular pants',

      nameIT: 'Panta Classico',
      slugIT: 'pantalone-classico',
      categoryIT: 'Pantaloni',
      descriptionIT: 'Un bel panta',

      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
    },
  ],
};

export default data;
